name: Daily Email

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1:00 UTC (~9AM Malaysia)
  workflow_dispatch:      # Manual trigger button

jobs:
  send-fact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Needed to push back to repo
          fetch-depth: 0             # Get full history
          ref: main                  # Make sure we're on the main branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send Email
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python main.py

      - name: Update quotes.txt
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add quotes.txt
          git commit -m "Update quotes.txt" || echo "Nothing to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
